import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar_admin from "@/components/sidebar_admin";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CineManager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {

  return (
    <html lang="fr" data-theme="light">
      <body className={inter.className}>
        <div className="flex-wrap">
          <div className="flex">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
